"""Description of changes

Revision ID: 9321ac6105d2
Revises: b47c8be4e6b8
Create Date: 2023-07-28 15:46:37.209072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9321ac6105d2'
down_revision = 'b47c8be4e6b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
