"""Description of changes

Revision ID: a748dd5072de
Revises: 1699a92bae3d
Create Date: 2023-07-31 13:14:21.156862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a748dd5072de'
down_revision = '1699a92bae3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    # ### end Alembic commands ###
