"""Description of changes

Revision ID: b47c8be4e6b8
Revises: f3a3335354cd
Create Date: 2023-07-28 15:45:48.465538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47c8be4e6b8'
down_revision = 'f3a3335354cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
