"""Description of changes

Revision ID: d47cd1b1db43
Revises: 9321ac6105d2
Create Date: 2023-07-28 15:48:31.241526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47cd1b1db43'
down_revision = '9321ac6105d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
