"""Description of changes

Revision ID: f3a3335354cd
Revises: 0e634e004faa
Create Date: 2023-07-28 15:33:08.234930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a3335354cd'
down_revision = '0e634e004faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('wallet', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wallet')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
