"""Remove unique constraint from password column

Revision ID: f5e6b5a61337
Revises: f7fafc390b4b
Create Date: 2023-07-31 12:52:57.422421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e6b5a61337'
down_revision = 'f7fafc390b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.drop_constraint('user_password_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_password_key', 'user', ['password'])
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
