"""Description of changes

Revision ID: fdd0638e1d8c
Revises: c9865d8bd584
Create Date: 2023-07-28 16:08:59.191730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd0638e1d8c'
down_revision = 'c9865d8bd584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
